FROM nvidia/cuda:12.8.1-cudnn-devel-ubuntu22.04

ENV TZ=US/Pacific
ENV DEBIAN_FRONTEND=noninteractive
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

# OpenGL support (replaces deprecated nvidia/cudagl)
RUN apt-get update --fix-missing && \
    apt-get install -y --no-install-recommends \
    libgl1-mesa-dev libglu1-mesa-dev libglew-dev libglfw3-dev mesa-utils \
    && rm -rf /var/lib/apt/lists/*

RUN apt-get update --fix-missing && \
    apt-get install -y \
    wget bzip2 ca-certificates curl git vim tmux g++ gcc build-essential cmake \
    checkinstall gfortran libjpeg8-dev libtiff5-dev pkg-config yasm \
    libavcodec-dev libavformat-dev libswscale-dev libdc1394-dev \
    libv4l-dev qtbase5-dev libgtk2.0-dev libtbb-dev libatlas-base-dev \
    libmp3lame-dev libtheora-dev libvorbis-dev libxvidcore-dev \
    libopencore-amrnb-dev libopencore-amrwb-dev v4l-utils \
    libprotobuf-dev protobuf-compiler libgoogle-glog-dev libgflags-dev \
    libgphoto2-dev libhdf5-dev doxygen libflann-dev libboost-all-dev \
    proj-data libproj-dev libyaml-cpp-dev cmake-curses-gui libzmq3-dev \
    freeglut3-dev \
    && rm -rf /var/lib/apt/lists/*

RUN cd / && git clone https://github.com/pybind/pybind11 && \
    cd pybind11 && git checkout v2.10.0 && \
    mkdir build && cd build && \
    cmake .. -DCMAKE_BUILD_TYPE=Release -DPYBIND11_INSTALL=ON -DPYBIND11_TEST=OFF && \
    make -j$(nproc) && make install

RUN cd / && wget https://gitlab.com/libeigen/eigen/-/archive/3.4.0/eigen-3.4.0.tar.gz && \
    tar xvzf ./eigen-3.4.0.tar.gz && \
    cd eigen-3.4.0 && mkdir build && cd build && cmake .. && make install

RUN cd / && wget --quiet https://github.com/conda-forge/miniforge/releases/latest/download/Miniforge3-Linux-x86_64.sh -O /miniforge.sh && \
    /bin/bash /miniforge.sh -b -p /opt/conda && \
    rm /miniforge.sh && \
    ln -s /opt/conda/etc/profile.d/conda.sh /etc/profile.d/conda.sh && \
    echo ". /opt/conda/etc/profile.d/conda.sh" >> ~/.bashrc && \
    /opt/conda/bin/conda update -n base -c conda-forge conda -y && \
    /opt/conda/bin/conda create -n my python=3.11 -y

ENV PIP=/opt/conda/envs/my/bin/pip
ENV PATH=/opt/conda/envs/my/bin:$PATH

# Install torch first in its own layer so pytorch3d can find it at build time
RUN $PIP install \
    torch==2.5.1+cu124 torchvision==0.20.1+cu124 torchaudio==2.5.1+cu124 \
    --index-url https://download.pytorch.org/whl/cu124

# --no-build-isolation lets pytorch3d's setup.py see the already-installed torch
RUN $PIP install --no-build-isolation \
    "git+https://github.com/facebookresearch/pytorch3d.git@stable"

RUN $PIP install \
    scipy joblib scikit-learn ruamel.yaml trimesh pyyaml \
    opencv-python imageio open3d transformations warp-lang einops kornia pyrender

RUN $PIP install kaolin==0.17.0 -f https://nvidia-kaolin.s3.us-east-2.amazonaws.com/torch-2.5.1_cu124.html

# RTX 4080 = Ada Lovelace = sm_89; must be set explicitly since docker build has no GPU access
ENV TORCH_CUDA_ARCH_LIST="8.9"

RUN cd / && git clone https://github.com/NVlabs/nvdiffrast && \
    cd /nvdiffrast && $PIP install --no-build-isolation .

ENV OPENCV_IO_ENABLE_OPENEXR=1

RUN $PIP install \
    scikit-image meshcat webdataset omegaconf pypng roma seaborn \
    opencv-contrib-python openpyxl wandb imgaug Ninja xlsxwriter timm \
    albumentations xatlas rtree jupyterlab objaverse ultralytics==8.0.120 \
    pycocotools videoio numba h5py

SHELL ["/bin/bash", "--login", "-c"]
ENV SHELL=/bin/bash
RUN ln -sf /bin/bash /bin/sh
RUN echo ". /opt/conda/etc/profile.d/conda.sh && conda activate my" >> ~/.bashrc
